// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type LoginMethod string

const (
	LoginMethodEmailPassword LoginMethod = "email_password"
	LoginMethodGoogleOauth   LoginMethod = "google_oauth"
	LoginMethodFacebookOauth LoginMethod = "facebook_oauth"
	LoginMethodGithubOauth   LoginMethod = "github_oauth"
)

func (e *LoginMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LoginMethod(s)
	case string:
		*e = LoginMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for LoginMethod: %T", src)
	}
	return nil
}

type NullLoginMethod struct {
	LoginMethod LoginMethod
	Valid       bool // Valid is true if LoginMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLoginMethod) Scan(value interface{}) error {
	if value == nil {
		ns.LoginMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LoginMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLoginMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LoginMethod), nil
}

type UserRole string

const (
	UserRoleUser  UserRole = "user"
	UserRoleAdmin UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

// Main user accounts table
type User struct {
	// Unique user identifier (UUID)
	ID pgtype.UUID
	// User email address (unique, required)
	Email string
	// Bcrypt/Argon2 hashed password (nullable for OAuth users)
	PasswordHash      pgtype.Text
	Username          pgtype.Text
	LoginMethod       LoginMethod
	FirstName         pgtype.Text
	LastName          pgtype.Text
	ProfilePictureUrl pgtype.Text
	Timezone          pgtype.Text
	// Whether the account is active (soft delete alternative)
	IsActive bool
	// Whether user has verified their email address
	EmailVerified bool
	Role          UserRole
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	LastLoginAt   pgtype.Timestamptz
}
