// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateUser = `-- name: ActivateUser :exec
UPDATE users
SET
  is_active = true,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) ActivateUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, activateUser, id)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByRole = `-- name: CountUsersByRole :one
SELECT COUNT(*) FROM users
WHERE role = $1
`

func (q *Queries) CountUsersByRole(ctx context.Context, role UserRole) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email,
  password_hash,
  username,
  login_method,
  first_name,
  last_name,
  profile_picture_url,
  timezone,
  is_active,
  email_verified,
  role
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, email, password_hash, username, login_method, first_name, last_name, profile_picture_url, timezone, is_active, email_verified, role, created_at, updated_at, last_login_at
`

type CreateUserParams struct {
	Email             string
	PasswordHash      pgtype.Text
	Username          pgtype.Text
	LoginMethod       LoginMethod
	FirstName         pgtype.Text
	LastName          pgtype.Text
	ProfilePictureUrl pgtype.Text
	Timezone          pgtype.Text
	IsActive          bool
	EmailVerified     bool
	Role              UserRole
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Username,
		arg.LoginMethod,
		arg.FirstName,
		arg.LastName,
		arg.ProfilePictureUrl,
		arg.Timezone,
		arg.IsActive,
		arg.EmailVerified,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.LoginMethod,
		&i.FirstName,
		&i.LastName,
		&i.ProfilePictureUrl,
		&i.Timezone,
		&i.IsActive,
		&i.EmailVerified,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users
SET
  is_active = false,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, email, password_hash, username, login_method, first_name, last_name, profile_picture_url, timezone, is_active, email_verified, role, created_at, updated_at, last_login_at FROM users
WHERE id = $1 LIMIT 1
`

// Users Table --
func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.LoginMethod,
		&i.FirstName,
		&i.LastName,
		&i.ProfilePictureUrl,
		&i.Timezone,
		&i.IsActive,
		&i.EmailVerified,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, username, login_method, first_name, last_name, profile_picture_url, timezone, is_active, email_verified, role, created_at, updated_at, last_login_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.LoginMethod,
		&i.FirstName,
		&i.LastName,
		&i.ProfilePictureUrl,
		&i.Timezone,
		&i.IsActive,
		&i.EmailVerified,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, password_hash, username, login_method, first_name, last_name, profile_picture_url, timezone, is_active, email_verified, role, created_at, updated_at, last_login_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.LoginMethod,
		&i.FirstName,
		&i.LastName,
		&i.ProfilePictureUrl,
		&i.Timezone,
		&i.IsActive,
		&i.EmailVerified,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listActiveUsers = `-- name: ListActiveUsers :many
SELECT id, email, password_hash, username, login_method, first_name, last_name, profile_picture_url, timezone, is_active, email_verified, role, created_at, updated_at, last_login_at FROM users
WHERE is_active = true
ORDER BY created_at DESC
`

func (q *Queries) ListActiveUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Username,
			&i.LoginMethod,
			&i.FirstName,
			&i.LastName,
			&i.ProfilePictureUrl,
			&i.Timezone,
			&i.IsActive,
			&i.EmailVerified,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, username, login_method, first_name, last_name, profile_picture_url, timezone, is_active, email_verified, role, created_at, updated_at, last_login_at FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Username,
			&i.LoginMethod,
			&i.FirstName,
			&i.LastName,
			&i.ProfilePictureUrl,
			&i.Timezone,
			&i.IsActive,
			&i.EmailVerified,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByRole = `-- name: ListUsersByRole :many
SELECT id, email, password_hash, username, login_method, first_name, last_name, profile_picture_url, timezone, is_active, email_verified, role, created_at, updated_at, last_login_at FROM users
WHERE role = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUsersByRole(ctx context.Context, role UserRole) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Username,
			&i.LoginMethod,
			&i.FirstName,
			&i.LastName,
			&i.ProfilePictureUrl,
			&i.Timezone,
			&i.IsActive,
			&i.EmailVerified,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersByEmail = `-- name: SearchUsersByEmail :many
SELECT id, email, password_hash, username, login_method, first_name, last_name, profile_picture_url, timezone, is_active, email_verified, role, created_at, updated_at, last_login_at FROM users
WHERE email ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchUsersByEmailParams struct {
	Column1 pgtype.Text
	Limit   int32
	Offset  int32
}

func (q *Queries) SearchUsersByEmail(ctx context.Context, arg SearchUsersByEmailParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsersByEmail, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Username,
			&i.LoginMethod,
			&i.FirstName,
			&i.LastName,
			&i.ProfilePictureUrl,
			&i.Timezone,
			&i.IsActive,
			&i.EmailVerified,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersByName = `-- name: SearchUsersByName :many
SELECT id, email, password_hash, username, login_method, first_name, last_name, profile_picture_url, timezone, is_active, email_verified, role, created_at, updated_at, last_login_at FROM users
WHERE
  first_name ILIKE '%' || $1 || '%' OR
  last_name ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchUsersByNameParams struct {
	Column1 pgtype.Text
	Limit   int32
	Offset  int32
}

func (q *Queries) SearchUsersByName(ctx context.Context, arg SearchUsersByNameParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsersByName, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Username,
			&i.LoginMethod,
			&i.FirstName,
			&i.LastName,
			&i.ProfilePictureUrl,
			&i.Timezone,
			&i.IsActive,
			&i.EmailVerified,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET
  last_login_at = CURRENT_TIMESTAMP,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET
  email = $2,
  username = $3,
  first_name = $4,
  last_name = $5,
  profile_picture_url = $6,
  timezone = $7,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateUserParams struct {
	ID                pgtype.UUID
	Email             string
	Username          pgtype.Text
	FirstName         pgtype.Text
	LastName          pgtype.Text
	ProfilePictureUrl pgtype.Text
	Timezone          pgtype.Text
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.ProfilePictureUrl,
		arg.Timezone,
	)
	return err
}

const updateUserLoginMethod = `-- name: UpdateUserLoginMethod :exec
UPDATE users
SET
  login_method = $2,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateUserLoginMethodParams struct {
	ID          pgtype.UUID
	LoginMethod LoginMethod
}

func (q *Queries) UpdateUserLoginMethod(ctx context.Context, arg UpdateUserLoginMethodParams) error {
	_, err := q.db.Exec(ctx, updateUserLoginMethod, arg.ID, arg.LoginMethod)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET
  password_hash = $2,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID
	PasswordHash pgtype.Text
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users
SET
  role = $2,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   pgtype.UUID
	Role UserRole
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users
SET
  email_verified = true,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, id)
	return err
}
